#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "usage: counstr objfile"
fi
obj=$1

cmd="llvm-objdump --disassemble --section=.text $obj"
dis=$($cmd)
start=$(echo "$dis" | awk '/_JIT_ENTRY/ {print FNR}')
ninstr=$(echo "$dis" | tail -n +$start | wc -l)

echo "$dis"
echo "There are $ninstr instructions"
