#!/usr/bin/env bash

$READOBJ --elf-output-style=JSON \
             --expand-relocs \
             --section-data \
             --section-relocations \
             --section-symbols \
             --sections \
             $1
             # --pretty-print \
             # --symbols \
             # --demangle \
             # --section-details \
             # --section-headers \
             # --section-mapping \
